name: mobile_app

dependencies:
  flutter:
    sdk: flutter

  # For API calls
  dio: ^5.3.3

  # For state management (choose one)
  provider: ^6.0.5
  # or
  # flutter_riverpod: ^2.4.5

  # For data visualization/charts
  fl_chart: ^0.64.0

  # For local storage
  shared_preferences: ^2.2.2

  # For push notifications (optional for now)
  # firebase_core: ^2.17.0
  # firebase_messaging: ^14.6.9

  # For UI icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

environment:
  sdk: '^3.9.0'